spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.229.47.27:3306/mrbs?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minIdle: 5
    maxActive: 15
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 30000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    logSlowSql: true
    validationQuery: SELECT 1
  flyway:
    enabled: true   #默认就是true，写在这里只是为了知道有这么个配置
    clean-disabled: true
# liscva-security配置
liscva:
  security:
    # token名称 (同时也是cookie名称)
    token-name: liscva
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    is-concurrent: false
    # 是否输出操作日志
    is-log: true
#spring:
#  # redis配置
#  redis:
#    # Redis数据库索引（默认为0）
#    database: 15
#    # Redis服务器地址
#    host: 127.0.0.1
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password: 123456
#    # 连接超时时间
#    timeout: 10s
#    lettuce:
#      pool:
#        # 连接池最大连接数
#        max-active: 200
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
#        # 连接池中的最大空闲连接
#        max-idle: 10
#        # 连接池中的最小空闲连接
#        min-idle: 0