# curl -X POST -H 'Content-Type: application/json; charset=utf-8' -i /mrReserve/reserveMettingRoom.htm --data '{
#  "reserveId": 333,
#  "areaId": 26,
#  "reserveTodo": "c3zc4s",
#  "dayTimeDto": {
#    "day": "m21f6h",
#    "startTime": "2021-09-23 16:40:21",
#    "endTime": "2021-09-23 16:40:21"
#  },
#  "reserveUser": {
#    "userId": 556,
#    "userName": "elliot.bradtke"
#  }
#}'
POST localhost:8080/mrReserve/reserveMettingRoom.htm
Content-Type: application/json; charset=utf-8

{
  "areaId": 1,
  "reserveTodo": "c3zc4s",
  "dayTimeDto": {
    "day": "2021-09-23",
    "startTime": "10:30",
    "endTime": "12:00"
  },
  "reserveUser": {
    "userCode": 556,
    "userName": "elliot.bradtke"
  }
}

###





